# 使用官方的 Node 作為基礎映像
FROM node:19-alpine

# 設定工作目錄
WORKDIR /app

# 更新npm套件
# RUN npm update
RUN npm install -g npm@9.7.2
RUN npm install consolidate@latest

# 安裝vue-cli
RUN npm install -g @vue/cli-service

# 複製 package.json 和 package-lock.json 並安裝相依套件
COPY package*.json ./
RUN npm install

# 複製專案所有檔案到容器中
# COPY . . # 改用docker-compose volume

# 更新Vue
# RUN npm i vue@3.2.26
# RUN npm install vue@3.2.26
# RUN npm install @vue/compiler-sfc

# 建置 Vue CLI 專案W
# RUN npm run build

# 定義容器啟動時執行的指令
CMD [ "npm", "run", "serve"]