FROM python:3.10.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

CMD ["uvicorn", "app.main:app" , "--reload", "--host", "0.0.0.0", "--port", "8000"]